import type { Product } from "@/types/product";

export const seedProducts: Product[] = [

  // ── CHANEL ──────────────────────────────────────────────────────────────────

  {
    id: "1892213",
    slug: "chanel-lambskin-mini-pearl-crush-flap-dark-grey-1892213",
    brand: "Chanel",
    name: "Lambskin Mini Pearl Crush Rectangular Flap Dark Grey",
    price: 5395,
    estRetail: 7200,
    savingsPercent: 25,
    condition: "Excellent",
    color: "Grey",
    material: "Leather",
    bagType: "Crossbody Bags",
    images: [
      "https://cdn.shopify.com/s/files/1/0894/3186/7695/files/762f25b75ef7a6c0ba626e6fc8bf39a6_ad243b85-721b-44fa-9425-a169342f9df2.jpg?v=1779645023",
    ],
    description:
      "This is an authentic CHANEL Lambskin Quilted CC Pearl Crush Mini Rectangular Flap in Dark Grey. Crafted in soft quilted lambskin leather in dark grey, this coveted design features the signature gold CC turn-lock closure and a gold chain-link leather-threaded shoulder strap. The Pearl Crush collection adds a distinctive pearlised texture to Chanel's classic quilting.",
    itemNumber: "1892213",
    exterior: "Minor surface scuffs consistent with careful use",
    hardware: "Light surface scratches on gold-tone hardware",
    interior: "Clean leather lining, no marks or odour",
    comesWith: "Museum Grades Certificate of Authenticity, chain strap, dust bag",
    size: { base: '5.5"', height: '3.5"', depth: '2"', drop: '21"' },
  },
  {
    id: "1890767",
    slug: "chanel-caviar-quilted-petit-timeless-tote-ptt-black-1890767",
    brand: "Chanel",
    name: "Caviar Quilted Petit Timeless Tote PTT Black",
    price: 2495,
    estRetail: 3900,
    savingsPercent: 36,
    condition: "Excellent",
    color: "Black",
    material: "Leather",
    bagType: "Totes",
    images: [
      "https://cdn.shopify.com/s/files/1/0894/3186/7695/files/59bc6a9eaf6abd6de7e339794d992b29.jpg?v=1779558374",
    ],
    description:
      "This is an authentic CHANEL Caviar Quilted Petit Timeless Tote PTT in Black. Crafted of luxurious diamond quilted caviar leather in black, this compact tote is one of Chanel's most practical and enduring silhouettes. Features a gold-tone interlocking CC push-lock closure, woven chain and leather handles, and a spacious interior with zip and patch pockets.",
    itemNumber: "1890767",
    exterior: "Minor corner wear consistent with careful use",
    hardware: "Light wear on gold-tone hardware",
    interior: "Clean burgundy leather lining",
    comesWith: "Museum Grades Certificate of Authenticity, dust bag",
    size: { base: '12"', height: '8.5"', depth: '4.5"', drop: '9"' },
  },
  {
    id: "1848785",
    slug: "chanel-aged-calfskin-quilted-small-gabrielle-backpack-black-1848785",
    brand: "Chanel",
    name: "Aged Calfskin Quilted Small Gabrielle Backpack Black",
    price: 3195,
    estRetail: 4200,
    savingsPercent: 24,
    condition: "Excellent",
    color: "Black",
    material: "Leather",
    bagType: "Backpacks",
    images: [
      "https://cdn.shopify.com/s/files/1/0894/3186/7695/files/4d019a4a19f34314c0a44303059ca851.jpg?v=1775296971",
      "https://cdn.shopify.com/s/files/1/0894/3186/7695/files/6575063789a6a74aee19d33536d0d9e4.jpg?v=1775296971",
    ],
    description:
      "This is an authentic CHANEL Aged Calfskin Quilted Small Gabrielle Backpack in Black. Crafted of aged calfskin leather in a mixed quilting pattern, this versatile design features a top handle, adjustable backpack straps, and a zip top. The signature Chanel hardware at the front fastens a flap pocket. An elegant everyday backpack from Chanel's sporty-chic Gabrielle line.",
    itemNumber: "1848785",
    exterior: "Minor surface wear consistent with careful use",
    hardware: "Light scratches on gold and silver mixed hardware",
    interior: "Clean microfibre lining",
    comesWith: "Museum Grades Certificate of Authenticity, dust bag",
    size: { base: '7.5"', height: '10"', depth: '4"', drop: '16"' },
  },
  {
    id: "1861531",
    slug: "chanel-aged-calfskin-quilted-small-gabrielle-backpack-blue-1861531",
    brand: "Chanel",
    name: "Aged Calfskin Quilted Small Gabrielle Backpack Blue",
    price: 2940,
    estRetail: 4200,
    savingsPercent: 30,
    condition: "Excellent",
    color: "Blue",
    material: "Leather",
    bagType: "Backpacks",
    images: [
      "https://cdn.shopify.com/s/files/1/0894/3186/7695/files/f0e166e76deb4372999d0739bd992d83.jpg?v=1776447119",
      "https://cdn.shopify.com/s/files/1/0894/3186/7695/files/507c3ff5c97fa4a4dfb9522451a2249b.jpg?v=1776447119",
    ],
    description:
      "This is an authentic CHANEL Aged Calfskin Quilted Small Gabrielle Backpack in Blue. Crafted of aged calfskin in a rich navy blue with a mixed quilting pattern that blends Chanel's classic diamond and herringbone motifs. Features a top handle, adjustable backpack straps, a zip top, and a front flap pocket secured by mixed gold and silver hardware.",
    itemNumber: "1861531",
    exterior: "Minor surface wear, faint scuffs on base",
    hardware: "Light marks on mixed hardware",
    interior: "Clean microfibre lining",
    comesWith: "Museum Grades Certificate of Authenticity, dust bag",
    size: { base: '7.5"', height: '10"', depth: '4"', drop: '16"' },
  },
  {
    id: "1845013",
    slug: "chanel-aged-calfskin-quilted-small-gabrielle-backpack-orange-1845013",
    brand: "Chanel",
    name: "Aged Calfskin Quilted Small Gabrielle Backpack Orange",
    price: 3055,
    estRetail: 4200,
    savingsPercent: 27,
    condition: "Excellent",
    color: "Orange",
    material: "Leather",
    bagType: "Backpacks",
    images: [
      "https://cdn.shopify.com/s/files/1/0894/3186/7695/files/e61580d916cdac6f6b199096eca3a645.jpg?v=1774563036",
      "https://cdn.shopify.com/s/files/1/0894/3186/7695/files/f3f985cffad019166ee8b0f8d5433a6a.jpg?v=1774563035",
    ],
    description:
      "This is an authentic CHANEL Aged Calfskin Quilted Small Gabrielle Backpack in Orange. A bold and striking colourway in aged calfskin leather with Chanel's signature mixed quilting. The bright tangerine orange makes this one of the most collectible colourways of the Gabrielle line. Features adjustable backpack straps, top handle, and mixed gold and silver hardware.",
    itemNumber: "1845013",
    exterior: "Minor surface wear consistent with careful use",
    hardware: "Light scratches on mixed hardware",
    interior: "Clean microfibre lining",
    comesWith: "Museum Grades Certificate of Authenticity, dust bag",
    size: { base: '7.5"', height: '10"', depth: '4"', drop: '16"' },
  },
  {
    id: "1890834",
    slug: "chanel-aged-calfskin-quilted-small-gabrielle-bucket-black-1890834",
    brand: "Chanel",
    name: "Aged Calfskin Quilted Small Gabrielle Bucket Black",
    price: 3650,
    estRetail: 5200,
    savingsPercent: 30,
    condition: "Excellent",
    color: "Black",
    material: "Leather",
    bagType: "Bucket Bags",
    images: [
      "https://cdn.shopify.com/s/files/1/0894/3186/7695/files/c902299398087641b5cccb93382a94ad_cd777946-b11d-42aa-8983-4128f042e791.jpg?v=1779320045",
      "https://cdn.shopify.com/s/files/1/0894/3186/7695/files/0844208e26b29096550bb7f86c300db3_b9752c08-8d83-4d37-a4d3-a46f21821455.jpg?v=1779320044",
    ],
    description:
      "This is an authentic CHANEL Aged Calfskin Quilted Small Gabrielle Bucket in Black. Crafted of aged calfskin leather in black with a mixed diamond and chevron quilting pattern, this bucket silhouette is one of the rarest forms from the Gabrielle line. Features a drawstring closure, mixed gold and silver hardware, and an adjustable chain-and-leather strap.",
    itemNumber: "1890834",
    exterior: "Minor surface wear consistent with use",
    hardware: "Light scratches on mixed gold and silver hardware",
    interior: "Clean microfibre lining",
    comesWith: "Museum Grades Certificate of Authenticity, adjustable strap, dust bag",
    size: { base: '8"', height: '9"', depth: '5"', drop: '20"' },
  },
  {
    id: "1882349",
    slug: "chanel-calfskin-braided-medium-boy-flap-black-1882349",
    brand: "Chanel",
    name: "Calfskin Braided Medium Boy Flap Black",
    price: 3595,
    estRetail: 5500,
    savingsPercent: 35,
    condition: "Excellent",
    color: "Black",
    material: "Leather",
    bagType: "Shoulder Bags",
    images: [
      "https://cdn.shopify.com/s/files/1/0894/3186/7695/files/eb6d22d77f585064157ba4c45a06bafe.jpg?v=1778862670",
      "https://cdn.shopify.com/s/files/1/0894/3186/7695/files/57a2f5fb8d79f4ae2360249d5f103a27.jpg?v=1778862669",
    ],
    description:
      "This is an authentic CHANEL Calfskin Braided Medium Boy Flap in Black. Crafted of smooth black calfskin leather with a distinctive braided trim detail framing the flap — an elevated variation on the iconic Boy Chanel silhouette. Features the signature ruthenium CC turn-lock closure, a braided chain shoulder strap with leather pad, and a structured interior.",
    itemNumber: "1882349",
    exterior: "Minor surface wear, light scuffs on edges",
    hardware: "Light marks on ruthenium-tone hardware",
    interior: "Clean burgundy leather lining",
    comesWith: "Museum Grades Certificate of Authenticity, chain strap, dust bag",
    size: { base: '10"', height: '7"', depth: '3.5"', drop: '20"' },
  },
  {
    id: "1861176",
    slug: "chanel-calfskin-braided-small-boy-flap-black-1861176",
    brand: "Chanel",
    name: "Calfskin Braided Small Boy Flap Black",
    price: 3130,
    estRetail: 4800,
    savingsPercent: 35,
    condition: "Excellent",
    color: "Black",
    material: "Leather",
    bagType: "Shoulder Bags",
    images: [
      "https://cdn.shopify.com/s/files/1/0894/3186/7695/files/d86815717268a9070e106b3d110cc48f.jpg?v=1776506621",
      "https://cdn.shopify.com/s/files/1/0894/3186/7695/files/b3804ce0cc0b37f67bcb13cb4b32af7a.jpg?v=1776506621",
    ],
    description:
      "This is an authentic CHANEL Calfskin Braided Small Boy Flap in Black. The compact Boy Chanel silhouette rendered in smooth black calfskin with a braided leather border framing the iconic quilted flap. Features the signature CC push-lock closure, braided chain strap with leather pad, and a sleek structured interior. A refined variation on a modern Chanel classic.",
    itemNumber: "1861176",
    exterior: "Minor corner wear consistent with careful use",
    hardware: "Light scratches on ruthenium-tone hardware",
    interior: "Clean burgundy leather lining",
    comesWith: "Museum Grades Certificate of Authenticity, chain strap, dust bag",
    size: { base: '8"', height: '5"', depth: '2.5"', drop: '20"' },
  },
  {
    id: "1753898",
    slug: "chanel-calfskin-bubble-quilt-bowler-black-1753898",
    brand: "Chanel",
    name: "Calfskin Bubble Quilt Bowler Black",
    price: 1105,
    estRetail: 0,
    savingsPercent: 0,
    condition: "Excellent",
    color: "Black",
    material: "Leather",
    bagType: "Handbags",
    images: [
      "https://cdn.shopify.com/s/files/1/0894/3186/7695/files/51ebbfe854d63392e3472ca14e4df268.jpg?v=1767781694",
      "https://cdn.shopify.com/s/files/1/0894/3186/7695/files/625eeedcaa9b53009eff0fd71eb75054.jpg?v=1767781693",
    ],
    description:
      "This is an authentic CHANEL Calfskin Bubble Quilt Bowler in Black. Crafted of smooth black calfskin leather with three-dimensional bubble quilting — a distinctive puffed quilting motif that creates a sculptural, tactile surface unlike any other Chanel style. Features dual rolled leather top handles, a top zip closure, and silver-tone hardware. A collectible discontinued silhouette.",
    itemNumber: "1753898",
    exterior: "Minor surface wear, light marks on handles",
    hardware: "Light scratches on silver-tone hardware",
    interior: "Clean leather lining",
    comesWith: "Museum Grades Certificate of Authenticity, dust bag",
    size: { base: '12"', height: '8"', depth: '5.5"', drop: '4"' },
  },
  {
    id: "1763832",
    slug: "chanel-calfskin-bubble-quilt-bowler-brown-1763832",
    brand: "Chanel",
    name: "Calfskin Bubble Quilt Bowler Brown",
    price: 2325,
    estRetail: 0,
    savingsPercent: 0,
    condition: "Excellent",
    color: "Brown",
    material: "Leather",
    bagType: "Handbags",
    images: [
      "https://cdn.shopify.com/s/files/1/0894/3186/7695/files/49fa140eef4a7449f39a9c5084ebf8f2.jpg?v=1764880386",
      "https://cdn.shopify.com/s/files/1/0894/3186/7695/files/84f421a25ce2217e2938b878ff32ff1c.jpg?v=1764880386",
    ],
    description:
      "This is an authentic CHANEL Calfskin Bubble Quilt Bowler in Brown. A warm cognac brown calfskin leather with three-dimensional bubble quilting — an archive Chanel silhouette prized by collectors. The puffed quilting panels give this bowler bag a sculptural, modern feel. Features dual rolled leather top handles, a zip top closure, and gold-tone hardware.",
    itemNumber: "1763832",
    exterior: "Minor surface wear consistent with age",
    hardware: "Light patina on gold-tone hardware",
    interior: "Clean leather lining",
    comesWith: "Museum Grades Certificate of Authenticity, dust bag",
    size: { base: '12"', height: '8"', depth: '5.5"', drop: '4"' },
  },

  // ── SAINT LAURENT ────────────────────────────────────────────────────────────

  {
    id: "1673543",
    slug: "saint-laurent-lambskin-chevron-quilted-mini-loulou-hortensia-1673543",
    brand: "Saint Laurent",
    name: "Lambskin Chevron Quilted Mini Loulou Hortensia",
    price: 1935,
    estRetail: 2600,
    savingsPercent: 26,
    condition: "Excellent",
    color: "Pink",
    material: "Leather",
    bagType: "Crossbody Bags",
    images: [
      "https://cdn.shopify.com/s/files/1/0894/3186/7695/files/cb79f33173b72fe5ccc986f42737dfd1.jpg?v=1764797720",
      "https://cdn.shopify.com/s/files/1/0894/3186/7695/files/64e065cbb22453d4766273016b21fc09.jpg?v=1764797720",
    ],
    description:
      "This is an authentic SAINT LAURENT Lambskin Chevron Quilted Mini Loulou in Hortensia. Crafted of beautiful quilted lambskin leather in a rich reddish-purple, the Mini Loulou is one of YSL's most enduring designs. Features an aged gold YSL logo on the face, a gold chain-link strap with leather pad, and a flap with magnetic snap closure. Interior in black suede with a zip pocket.",
    itemNumber: "1673543",
    exterior: "Minor surface wear, light scuffs at corners",
    hardware: "Light scratches on aged gold-tone hardware",
    interior: "Clean black suede lining",
    comesWith: "Museum Grades Certificate of Authenticity, chain strap, dust bag",
    size: { base: '6"', height: '4.5"', depth: '2.5"', drop: '22"' },
  },
  {
    id: "1737684",
    slug: "saint-laurent-calfskin-small-sac-de-jour-black-1737684",
    brand: "Saint Laurent",
    name: "Calfskin Small Sac De Jour Black",
    price: 1315,
    estRetail: 1990,
    savingsPercent: 34,
    condition: "Excellent",
    color: "Black",
    material: "Leather",
    bagType: "Totes",
    images: [
      "https://cdn.shopify.com/s/files/1/0894/3186/7695/files/27e65280c37a4da0964ba296d7030b8e.jpg?v=1767340952",
      "https://cdn.shopify.com/s/files/1/0894/3186/7695/files/30086a053a4a26f37bc3056685e56c6f.jpg?v=1767340953",
    ],
    description:
      "This is an authentic SAINT LAURENT Calfskin Small Sac De Jour in Black. Elegant and structured, the Sac De Jour is one of Yves Saint Laurent's most refined everyday bags. Crafted of smooth black calfskin leather with rolled leather top handles, an optional crossbody strap, and a top zip closure. The clean lines and minimal hardware make this one of the house's most timeless silhouettes.",
    itemNumber: "1737684",
    exterior: "Minor corner wear consistent with careful use",
    hardware: "Light wear on gold-tone hardware",
    interior: "Clean partitioned leather lining",
    comesWith: "Museum Grades Certificate of Authenticity, shoulder strap, dust bag",
    size: { base: '11"', height: '8"', depth: '4"', drop: '5"' },
  },
  {
    id: "1680354",
    slug: "saint-laurent-grain-de-poudre-chevron-medium-tribeca-shopping-bag-rouge-legion-1680354",
    brand: "Saint Laurent",
    name: "Grain de Poudre Matelasse Chevron Medium Tribeca Shopping Bag Rouge Legion",
    price: 1220,
    estRetail: 1800,
    savingsPercent: 32,
    condition: "Excellent",
    color: "Red",
    material: "Leather",
    bagType: "Shoulder Bags",
    images: [
      "https://cdn.shopify.com/s/files/1/0894/3186/7695/files/52e390c7a5951ec20bee47697ca253c9.jpg?v=1765399029",
      "https://cdn.shopify.com/s/files/1/0894/3186/7695/files/18d7a7df30738b9c95928cefb12c4456.jpg?v=1765399029",
    ],
    description:
      "This is an authentic SAINT LAURENT Grain de Poudre Matelasse Chevron Medium Tribeca Shopping Bag in Rouge Legion. Crafted of grain de poudre textured leather with striking chevron quilting on both faces and smooth leather sides. Features long gold bijoux chain shoulder straps, a zip top closure, and an interior with multiple pockets. A bold statement piece.",
    itemNumber: "1680354",
    exterior: "Minor surface wear consistent with use",
    hardware: "Light wear on gold-tone bijoux hardware",
    interior: "Clean suede lining",
    comesWith: "Museum Grades Certificate of Authenticity, dust bag",
    size: { base: '12"', height: '11"', depth: '6"', drop: '9"' },
  },
  {
    id: "1633704",
    slug: "saint-laurent-suede-calfskin-medium-monogram-sunset-dark-beige-1633704",
    brand: "Saint Laurent",
    name: "Suede Calfskin Medium Monogram Sunset Dark Beige",
    price: 1095,
    estRetail: 1690,
    savingsPercent: 35,
    condition: "Excellent",
    color: "Beige",
    material: "Leather",
    bagType: "Shoulder Bags",
    images: [
      "https://cdn.shopify.com/s/files/1/0894/3186/7695/files/83a5502e81fedf05bdfff0cfa26b9873.jpg?v=1764850172",
      "https://cdn.shopify.com/s/files/1/0894/3186/7695/files/f81ae0bd91369a2d12e44c189330e119.jpg?v=1764850173",
    ],
    description:
      "This is an authentic SAINT LAURENT Suede Calfskin Medium Monogram Sunset in Dark Beige. Crafted of warm beige calfskin with a suede front flap, this shoulder bag features the signature aged gold YSL monogram closure, a chain strap with leather shoulder pad, and a rear patch pocket. The Sunset's clean triangular silhouette has made it one of YSL's most iconic bag shapes.",
    itemNumber: "1633704",
    exterior: "Minor surface wear, faint scuffs at base corners",
    hardware: "Light scratches on aged gold-tone hardware",
    interior: "Clean suede lining",
    comesWith: "Museum Grades Certificate of Authenticity, chain strap, dust bag",
    size: { base: '11"', height: '8"', depth: '3"', drop: '22"' },
  },
  {
    id: "1591713",
    slug: "saint-laurent-calfskin-crocodile-embossed-medium-monogram-sunset-black-1591713",
    brand: "Saint Laurent",
    name: "Calfskin Crocodile Embossed Medium Monogram Sunset Black",
    price: 1135,
    estRetail: 1690,
    savingsPercent: 33,
    condition: "Excellent",
    color: "Black",
    material: "Leather",
    bagType: "Shoulder Bags",
    images: [
      "https://cdn.shopify.com/s/files/1/0894/3186/7695/files/b340fc26b8334eb3bf0679eed7fde546.jpg?v=1764864042",
      "https://cdn.shopify.com/s/files/1/0894/3186/7695/files/d7cdb2e3787c9ac3d505459ff02924ff.jpg?v=1764864042",
    ],
    description:
      "This is an authentic SAINT LAURENT Calfskin Crocodile Embossed Medium Monogram Sunset in Black. Crafted of crocodile-embossed calfskin leather in black with a silver chain link shoulder strap and leather pad. Features a rear patch pocket, the signature YSL monogram closure, and an interior with card slots. The Sunset's clean triangular silhouette with a textured finish.",
    itemNumber: "1591713",
    exterior: "Minor surface wear consistent with careful use",
    hardware: "Light scratches on silver-tone hardware",
    interior: "Clean suede lining",
    comesWith: "Museum Grades Certificate of Authenticity, chain strap, dust bag",
    size: { base: '11"', height: '8"', depth: '3"', drop: '22"' },
  },
  {
    id: "1641461",
    slug: "saint-laurent-lambskin-quilted-toy-loulou-puffer-monogram-chain-satchel-crema-soft-1641461",
    brand: "Saint Laurent",
    name: "Lambskin Quilted Toy Loulou Puffer Monogram Chain Satchel Crema Soft",
    price: 1645,
    estRetail: 2350,
    savingsPercent: 30,
    condition: "Excellent",
    color: "White",
    material: "Leather",
    bagType: "Shoulder Bags",
    images: [
      "https://cdn.shopify.com/s/files/1/0894/3186/7695/files/aea95505901df29f7982007c93e3404b.jpg?v=1764850124",
      "https://cdn.shopify.com/s/files/1/0894/3186/7695/files/c059c44538afefa664a48a9ba4f6dfb1.jpg?v=1764850124",
    ],
    description:
      "This is an authentic SAINT LAURENT Lambskin Quilted Toy Loulou Puffer Monogram Chain Satchel in Crema Soft. Crafted of puffed quilted lambskin leather in creamy off-white, this petite satchel features aged silver chain link shoulder straps with leather pads, an aged silver YSL logo on the flap, and a magnetic snap closure. Interior in off-white suede.",
    itemNumber: "1641461",
    exterior: "Minor surface wear, light marks at corners",
    hardware: "Light scratches on aged silver-tone hardware",
    interior: "Clean off-white suede lining",
    comesWith: "Museum Grades Certificate of Authenticity, chain strap, dust bag",
    size: { base: '5"', height: '4"', depth: '2"', drop: '23"' },
  },
  {
    id: "1845183",
    slug: "saint-laurent-calfskin-matelasse-monogram-lou-camera-bag-black-1845183",
    brand: "Saint Laurent",
    name: "Calfskin Matelasse Monogram Lou Camera Bag Black",
    price: 1295,
    estRetail: 1790,
    savingsPercent: 28,
    condition: "Excellent",
    color: "Black",
    material: "Leather",
    bagType: "Crossbody Bags",
    images: [
      "https://cdn.shopify.com/s/files/1/0894/3186/7695/files/9686158e7c4251c8e58f6d849551a184.jpg?v=1774692212",
      "https://cdn.shopify.com/s/files/1/0894/3186/7695/files/ddedf0619ff4f037b9e9700c4f06e69c.jpg?v=1774692212",
    ],
    description:
      "This is an authentic SAINT LAURENT Calfskin Matelasse Monogram Lou Camera Bag in Black. Crafted of chevron-quilted calfskin leather in black, this compact camera bag features a leather shoulder strap, gold YSL logo on the face, and a top zip closure. The Lou's architectural rectangular form and clean quilting make it one of the most refined shapes in the YSL bag line.",
    itemNumber: "1845183",
    exterior: "Minor surface wear consistent with careful use",
    hardware: "Light marks on gold-tone hardware",
    interior: "Clean suede lining",
    comesWith: "Museum Grades Certificate of Authenticity, shoulder strap, dust bag",
    size: { base: '8"', height: '6"', depth: '2"', drop: '23"' },
  },
  {
    id: "1746003",
    slug: "saint-laurent-shearling-quilted-small-loulou-monogram-chain-satchel-cinnamon-1746003",
    brand: "Saint Laurent",
    name: "Shearling Quilted Small Loulou Monogram Chain Satchel Cinnamon",
    price: 1130,
    estRetail: 1990,
    savingsPercent: 43,
    condition: "Excellent",
    color: "Brown",
    material: "Leather",
    bagType: "Shoulder Bags",
    images: [
      "https://cdn.shopify.com/s/files/1/0894/3186/7695/files/7bc433b8a305008dd624b7da420df8de.jpg?v=1764847827",
      "https://cdn.shopify.com/s/files/1/0894/3186/7695/files/de8f4a301b09ff3da5d5e7b3bfd7948e.jpg?v=1764847827",
    ],
    description:
      "This is an authentic SAINT LAURENT Shearling Quilted Small Loulou Monogram Chain Satchel in Cinnamon. Crafted of luxurious natural shearling in a warm cinnamon brown with the signature Loulou quilting pattern, this rare seasonal version of the Loulou features aged silver chain link shoulder straps, an aged silver YSL logo, and a flap with magnetic snap closure.",
    itemNumber: "1746003",
    exterior: "Shearling in good condition, light wear on leather trim",
    hardware: "Light scratches on aged silver-tone hardware",
    interior: "Clean suede lining",
    comesWith: "Museum Grades Certificate of Authenticity, chain strap, dust bag",
    size: { base: '7"', height: '5"', depth: '2.5"', drop: '20"' },
  },
  {
    id: "1755701",
    slug: "saint-laurent-lambskin-chevron-quilted-mini-loulou-rouge-cabernet-1755701",
    brand: "Saint Laurent",
    name: "Lambskin Chevron Quilted Mini Loulou Rouge Cabernet",
    price: 1560,
    estRetail: 2200,
    savingsPercent: 29,
    condition: "Excellent",
    color: "Red",
    material: "Leather",
    bagType: "Crossbody Bags",
    images: [
      "https://cdn.shopify.com/s/files/1/0894/3186/7695/files/2d54b15c7492ee5ebe533488798b18a3.jpg?v=1764797777",
      "https://cdn.shopify.com/s/files/1/0894/3186/7695/files/3003d1d4f4878999cb702c1eb2e7d0ca.jpg?v=1764797777",
    ],
    description:
      "This is an authentic SAINT LAURENT Lambskin Chevron Quilted Mini Loulou in Rouge Cabernet. Crafted of soft quilted lambskin leather in a deep burgundy red, this Mini Loulou features the signature aged gold YSL logo on the face, a chain-link strap with leather pad, and a flap with magnetic snap closure. One of the most coveted colourways in the Loulou range.",
    itemNumber: "1755701",
    exterior: "Minor surface wear at corners",
    hardware: "Light scratches on aged gold-tone hardware",
    interior: "Clean black suede lining",
    comesWith: "Museum Grades Certificate of Authenticity, chain strap, dust bag",
    size: { base: '6"', height: '4.5"', depth: '2.5"', drop: '22"' },
  },
  {
    id: "1799618",
    slug: "saint-laurent-lambskin-quilted-maxi-icare-shopping-tote-black-1799618",
    brand: "Saint Laurent",
    name: "Lambskin Quilted Maxi Icare Shopping Tote Black",
    price: 4555,
    estRetail: 4750,
    savingsPercent: 4,
    condition: "Excellent",
    color: "Black",
    material: "Leather",
    bagType: "Totes",
    images: [
      "https://cdn.shopify.com/s/files/1/0894/3186/7695/files/4557c80a9a131c169c9303b01e0de679.jpg?v=1770140777",
      "https://cdn.shopify.com/s/files/1/0894/3186/7695/files/f5dbe1b17e83505c4fc078e86731470b.jpg?v=1770140768",
    ],
    description:
      "This is an authentic SAINT LAURENT Lambskin Quilted Maxi Icare Shopping Tote in Black. An oversized statement tote crafted of diamond-quilted lambskin leather in black with a monumental silhouette and the signature YSL logo at the front. Features long leather top handles and an open top. The Icare has become one of the most recognisable luxury totes of the decade.",
    itemNumber: "1799618",
    exterior: "Minor surface wear consistent with careful use",
    hardware: "Light wear on gold-tone hardware",
    interior: "Clean suede lining",
    comesWith: "Museum Grades Certificate of Authenticity, dust bag",
    size: { base: '20"', height: '16"', depth: '6"', drop: '8"' },
  },

  // ── HERMÈS ──────────────────────────────────────────────────────────────────

  {
    id: "1624917",
    slug: "hermes-epsom-kelly-sellier-25-vert-bosphore-1624917",
    brand: "Hermès",
    name: "Epsom Kelly Sellier 25 Vert Bosphore",
    price: 20990,
    estRetail: 0,
    savingsPercent: 0,
    condition: "Excellent",
    color: "Green",
    material: "Leather",
    bagType: "Handbags",
    images: [
      "https://cdn.shopify.com/s/files/1/0894/3186/7695/files/65db342c60a0bb3bb391b4fb4d5eecf0.jpg?v=1764850195",
      "https://cdn.shopify.com/s/files/1/0894/3186/7695/files/59287e50e70dbda2f627f215b7fb15db.jpg?v=1764850195",
    ],
    description:
      "This is an authentic HERMÈS Epsom Kelly Sellier 25 in Vert Bosphore. Crafted of Epsom calfskin leather — known for its fine cross-hatch grain and exceptional colour retention — in a vivid Aegean green. The Sellier construction features sharp, structured seams for a more architectural silhouette. Hardware in palladium finish. All closures function flawlessly.",
    itemNumber: "1624917",
    exterior: "Minor corner wear consistent with careful use",
    hardware: "Light surface scratches on palladium hardware",
    interior: "Clean Chevre lining, no marks or odour",
    comesWith: "Museum Grades Certificate of Authenticity, lock, key, clochette, dust bag, rain cover",
    size: { base: '10"', height: '8"', depth: '4"', drop: '3.5"' },
  },
  {
    id: "1605992",
    slug: "hermes-taurillon-clemence-picotin-lock-18-pm-nata-1605992",
    brand: "Hermès",
    name: "Taurillon Clemence Picotin Lock 18 PM Nata",
    price: 3795,
    estRetail: 0,
    savingsPercent: 0,
    condition: "Excellent",
    color: "White",
    material: "Leather",
    bagType: "Bucket Bags",
    images: [
      "https://cdn.shopify.com/s/files/1/0894/3186/7695/files/bf5fe95fb580a327222dacae1c11f898.jpg?v=1764880286",
      "https://cdn.shopify.com/s/files/1/0894/3186/7695/files/bf9b8d34eac6b87d1679c6a2d6c7ddb2.jpg?v=1764880286",
    ],
    description:
      "This is an authentic HERMÈS Taurillon Clemence Picotin Lock 18 PM in Nata. Crafted of Clemence calfskin leather — supple and slightly slouchy with a soft sheen — in a warm off-white (Nata). The Picotin's clean bucket silhouette features a single rolled leather top handle and polished palladium hardware at the fold-over closure. Effortlessly understated.",
    itemNumber: "1605992",
    exterior: "Minor surface wear consistent with careful use",
    hardware: "Light marks on palladium hardware",
    interior: "Clean leather lining",
    comesWith: "Museum Grades Certificate of Authenticity, lock, dust bag",
    size: { base: '7.5"', height: '7"', depth: '5"', drop: '4"' },
  },
  {
    id: "1701679",
    slug: "hermes-swift-kelly-moove-sesame-1701679",
    brand: "Hermès",
    name: "Swift Kelly Moove Sesame",
    price: 10195,
    estRetail: 0,
    savingsPercent: 0,
    condition: "Excellent",
    color: "Beige",
    material: "Leather",
    bagType: "Crossbody Bags",
    images: [
      "https://cdn.shopify.com/s/files/1/0894/3186/7695/files/3fec3bbdc0aaea6e54524ea404c7e717_e8d00758-abe9-4b9e-9efd-6792e9651ee6.jpg?v=1767649420",
      "https://cdn.shopify.com/s/files/1/0894/3186/7695/files/50b9b3616e16a5b8f8c65b484689555d_2ece8400-7d44-482a-9db9-c4015c890dd2.jpg?v=1767649419",
    ],
    description:
      "This is an authentic HERMÈS Swift Kelly Moove in Sesame. Crafted of Swift calfskin leather — smooth, fine-grained and luxuriously supple — in warm Sesame, a rich caramel beige. The Kelly Moove is a relaxed interpretation of the Kelly silhouette, featuring a lengthy crossbody strap and an attached coin purse. Palladium hardware throughout.",
    itemNumber: "1701679",
    exterior: "Minor surface wear at base corners",
    hardware: "Light marks on palladium hardware",
    interior: "Clean leather lining",
    comesWith: "Museum Grades Certificate of Authenticity, crossbody strap, dust bag",
    size: { base: '8"', height: '6.5"', depth: '4"', drop: '18"' },
  },
  {
    id: "1763170",
    slug: "hermes-evercolor-geta-beige-marfa-1763170",
    brand: "Hermès",
    name: "Evercolor Geta Beige Marfa",
    price: 5615,
    estRetail: 0,
    savingsPercent: 0,
    condition: "Excellent",
    color: "Beige",
    material: "Leather",
    bagType: "Crossbody Bags",
    images: [
      "https://cdn.shopify.com/s/files/1/0894/3186/7695/files/437aeff5d5e949aa37340d431459dc5e.jpg?v=1764846587",
      "https://cdn.shopify.com/s/files/1/0894/3186/7695/files/bc9be8c174c72ea894a526ff1e35a5df.jpg?v=1764846587",
    ],
    description:
      "This is an authentic HERMÈS Evercolor Geta in Beige Marfa. Crafted of Evercolor calfskin — a scratch-resistant, lightweight leather with a refined matte grain — in warm Beige Marfa. The Geta is a small, symmetrical messenger-style bag with a structured silhouette, adjustable leather strap, and palladium-tone clasp closure. An understated and practical Hermès everyday piece.",
    itemNumber: "1763170",
    exterior: "Minor surface wear consistent with use",
    hardware: "Light marks on palladium hardware",
    interior: "Clean leather lining",
    comesWith: "Museum Grades Certificate of Authenticity, adjustable strap, dust bag",
    size: { base: '6.5"', height: '5"', depth: '3"', drop: '18"' },
  },
  {
    id: "1839957",
    slug: "hermes-evercolor-constance-18-anemone-1839957",
    brand: "Hermès",
    name: "Evercolor Constance 18 Anemone",
    price: 9495,
    estRetail: 0,
    savingsPercent: 0,
    condition: "Excellent",
    color: "Purple",
    material: "Leather",
    bagType: "Shoulder Bags",
    images: [
      "https://cdn.shopify.com/s/files/1/0894/3186/7695/files/d504693e900a87334bfcc430058e7cdd.jpg?v=1773946786",
      "https://cdn.shopify.com/s/files/1/0894/3186/7695/files/8262171a226bac1ccfc7ed4c76b0674d.jpg?v=1773946786",
    ],
    description:
      "This is an authentic HERMÈS Evercolor Constance 18 in Anemone. Crafted of Evercolor calfskin leather in a vivid violet purple (Anemone), one of Hermès's most striking seasonal colours. The Constance 18 features the house's iconic H-clasp in palladium finish and a single crossbody strap. A slim, refined silhouette that epitomises Hermès elegance.",
    itemNumber: "1839957",
    exterior: "Minor surface wear consistent with careful use",
    hardware: "Light marks on palladium H-clasp hardware",
    interior: "Clean leather lining",
    comesWith: "Museum Grades Certificate of Authenticity, crossbody strap, dust bag",
    size: { base: '7"', height: '5.5"', depth: '1.5"', drop: '21"' },
  },
  {
    id: "1684524",
    slug: "hermes-togo-birkin-25-bronze-dore-1684524",
    brand: "Hermès",
    name: "Togo Birkin 25 Bronze Dore",
    price: 23285,
    estRetail: 0,
    savingsPercent: 0,
    condition: "Excellent",
    color: "Brown",
    material: "Leather",
    bagType: "Handbags",
    images: [
      "https://cdn.shopify.com/s/files/1/0894/3186/7695/files/b108a1f2f32fecc72e721acfa76e6ba8.jpg?v=1764849752",
      "https://cdn.shopify.com/s/files/1/0894/3186/7695/files/9544c3710f92064eb77febe987709762.jpg?v=1764849752",
    ],
    description:
      "This is an authentic HERMÈS Togo Birkin 25 in Bronze Dore. Crafted of Togo calfskin — the house's most popular leather, prized for its pebbled texture and resistance to scratches — in a deep warm bronze brown. The Birkin 25 is the smallest and most coveted size, hand-stitched in the Hermès atelier. Hardware in gold finish. All closures and the turn-lock function flawlessly.",
    itemNumber: "1684524",
    exterior: "Minor corner wear consistent with careful use",
    hardware: "Light surface scratches on gold hardware, expected with age",
    interior: "Clean Chevre lining, no marks or odour",
    comesWith: "Museum Grades Certificate of Authenticity, lock, key, clochette, dust bag, rain cover",
    size: { base: '10"', height: '8"', depth: '5"', drop: '3.5"' },
  },
  {
    id: "1776183",
    slug: "hermes-taurillon-clemence-alfred-35-etoupe-1776183",
    brand: "Hermès",
    name: "Taurillon Clemence Alfred 35 Etoupe",
    price: 2750,
    estRetail: 0,
    savingsPercent: 0,
    condition: "Excellent",
    color: "Grey",
    material: "Leather",
    bagType: "Crossbody Bags",
    images: [
      "https://cdn.shopify.com/s/files/1/0894/3186/7695/files/95ec4837bd5eeb7c539d7ad495c9eb76.jpg?v=1766091838",
      "https://cdn.shopify.com/s/files/1/0894/3186/7695/files/8618feefbcd051d0170e95290e0e034c.jpg?v=1766091838",
    ],
    description:
      "This is an authentic HERMÈS Taurillon Clemence Alfred 35 in Etoupe. Crafted of supple Taurillon Clemence leather in Etoupe — a warm, sophisticated greige — this messenger bag features an adjustable crossbody strap, a flap closure, and palladium hardware. The Alfred 35 is a refined, practical everyday bag with Hermès's signature craftsmanship throughout.",
    itemNumber: "1776183",
    exterior: "Minor surface wear at strap attachment points",
    hardware: "Light marks on palladium hardware",
    interior: "Clean leather lining",
    comesWith: "Museum Grades Certificate of Authenticity, adjustable strap, dust bag",
    size: { base: '14"', height: '10.5"', depth: '4"', drop: '20"' },
  },
  {
    id: "1805802",
    slug: "hermes-swift-kelly-pochette-clutch-black-1805802",
    brand: "Hermès",
    name: "Swift Kelly Pochette Clutch Black",
    price: 24165,
    estRetail: 0,
    savingsPercent: 0,
    condition: "Excellent",
    color: "Black",
    material: "Leather",
    bagType: "Clutches",
    images: [
      "https://cdn.shopify.com/s/files/1/0894/3186/7695/files/89115508f3fc5cd24d98f49bf27a8652.jpg?v=1769805794",
      "https://cdn.shopify.com/s/files/1/0894/3186/7695/files/322a7e71accc8a80587df1206cb46182.jpg?v=1769805794",
    ],
    description:
      "This is an authentic HERMÈS Swift Kelly Pochette Clutch in Black. Crafted of Swift calfskin leather in classic black — smooth, fine-grained, and richly lustrous — this ultra-slim clutch is based on the Kelly's iconic silhouette reduced to a flat envelope form. Features the signature turn-lock closure in palladium and a detachable wrist strap. Among the rarest and most sought-after pieces from Hermès.",
    itemNumber: "1805802",
    exterior: "Minor surface wear consistent with careful use",
    hardware: "Light marks on palladium turn-lock hardware",
    interior: "Clean Chevre lining",
    comesWith: "Museum Grades Certificate of Authenticity, wrist strap, dust bag",
    size: { base: '8.5"', height: '4.5"', depth: '1.5"', drop: '—' },
  },
  {
    id: "1597249",
    slug: "hermes-swift-kelly-retourne-35-blue-jean-1597249",
    brand: "Hermès",
    name: "Swift Kelly Retourne 35 Blue Jean",
    price: 8500,
    estRetail: 0,
    savingsPercent: 0,
    condition: "Excellent",
    color: "Blue",
    material: "Leather",
    bagType: "Handbags",
    images: [
      "https://cdn.shopify.com/s/files/1/0894/3186/7695/files/bb20e77cf7a88f1c5b9d520068678c31.jpg?v=1773694470",
      "https://cdn.shopify.com/s/files/1/0894/3186/7695/files/06a2d637d3a49ba6b7010ac4a1334ad8.jpg?v=1773694470",
    ],
    description:
      "This is an authentic HERMÈS Swift Kelly Retourne 35 in Blue Jean. Crafted of Swift calfskin leather in a vivid sky blue (Blue Jean) — one of the most beloved Hermès colours. The Retourne construction features soft, inward-facing seams for a more relaxed silhouette compared to the Sellier. Hardware in palladium finish. A landmark size and colourway for the Kelly family.",
    itemNumber: "1597249",
    exterior: "Minor corner wear consistent with careful use",
    hardware: "Light surface scratches on palladium hardware",
    interior: "Clean Chevre lining",
    comesWith: "Museum Grades Certificate of Authenticity, lock, key, clochette, shoulder strap, dust bag",
    size: { base: '14"', height: '11"', depth: '5.5"', drop: '4"' },
  },
  {
    id: "1768488",
    slug: "hermes-taurillon-clemence-evelyne-tpm-brique-rouge-pivoine-1768488",
    brand: "Hermès",
    name: "Taurillon Clemence Evelyne TPM Brique Rouge Pivoine",
    price: 2280,
    estRetail: 0,
    savingsPercent: 0,
    condition: "Excellent",
    color: "Red",
    material: "Leather",
    bagType: "Crossbody Bags",
    images: [
      "https://cdn.shopify.com/s/files/1/0894/3186/7695/files/e1c8b7553cc52798c0dc07a766ce3a90.jpg?v=1765019120",
      "https://cdn.shopify.com/s/files/1/0894/3186/7695/files/a60d139ec3a54ed0827e6a47c93d8cc7.jpg?v=1765019121",
    ],
    description:
      "This is an authentic HERMÈS Taurillon Clemence Evelyne TPM in Brique and Rouge Pivoine. Crafted of Taurillon Clemence leather in a rich brick red with Rouge Pivoine (hot pink) interior detailing — a rare two-tone combination. The Evelyne's perforated H motif at the back panel is both functional ventilation and signature detail. Features an adjustable crossbody strap.",
    itemNumber: "1768488",
    exterior: "Minor surface wear consistent with careful use",
    hardware: "Light marks on palladium hardware",
    interior: "Clean Rouge Pivoine leather lining",
    comesWith: "Museum Grades Certificate of Authenticity, adjustable strap, dust bag",
    size: { base: '6"', height: '7"', depth: '1.5"', drop: '22"' },
  },

  // ── PRADA ────────────────────────────────────────────────────────────────────

  {
    id: "1886868",
    slug: "prada-nylon-vela-saffiano-double-zip-crossbody-black-1886868",
    brand: "Prada",
    name: "Nylon Vela Saffiano Double Zip Crossbody Black",
    price: 950,
    estRetail: 1390,
    savingsPercent: 32,
    condition: "Excellent",
    color: "Black",
    material: "Nylon",
    bagType: "Crossbody Bags",
    images: [
      "https://cdn.shopify.com/s/files/1/0894/3186/7695/files/ea641141a547421ae9a3dc3533d912ba.jpg?v=1779895638",
      "https://cdn.shopify.com/s/files/1/0894/3186/7695/files/0e5c51bccb4fa037981488a3f43fcd8b.jpg?v=1779895638",
    ],
    description:
      "This is an authentic PRADA Nylon Vela Saffiano Double Zip Crossbody in Black. Crafted of Prada's signature lightweight nylon with Saffiano cross-grain leather trim in black. Features two zip compartments for organised storage, an adjustable crossbody strap, and the iconic Prada triangle logo. A practical and enduringly stylish piece from the house's signature nylon canon.",
    itemNumber: "1886868",
    exterior: "Minor surface wear consistent with careful use",
    hardware: "Light marks on silver-tone hardware",
    interior: "Clean nylon lining",
    comesWith: "Museum Grades Certificate of Authenticity, adjustable strap, dust bag",
    size: { base: '10"', height: '7"', depth: '3"', drop: '22"' },
  },
  {
    id: "1886630",
    slug: "prada-city-calfskin-tie-dye-print-mini-odette-backpack-white-pink-black-1886630",
    brand: "Prada",
    name: "City Calfskin Tie Dye Print Mini Odette Backpack White Pink Black",
    price: 1295,
    estRetail: 1950,
    savingsPercent: 34,
    condition: "Excellent",
    color: "White",
    material: "Leather",
    bagType: "Backpacks",
    images: [
      "https://cdn.shopify.com/s/files/1/0894/3186/7695/files/adc8fb5606999b992f3c7cb3e029475b.jpg?v=1779895608",
      "https://cdn.shopify.com/s/files/1/0894/3186/7695/files/a791d00f8a51c184ab534e66e9f8253c.jpg?v=1779895608",
    ],
    description:
      "This is an authentic PRADA City Calfskin Tie Dye Print Mini Odette Backpack in White, Pink, and Black. Crafted of smooth city calfskin leather in white with an abstract tie dye print in pink and black — a playful, limited print from Prada's seasonal collection. Features adjustable backpack straps, a top handle, and the signature Prada triangle logo. Clean and minimal in form.",
    itemNumber: "1886630",
    exterior: "Minor surface wear consistent with careful use",
    hardware: "Light marks on gold-tone hardware",
    interior: "Clean leather lining",
    comesWith: "Museum Grades Certificate of Authenticity, dust bag",
    size: { base: '7"', height: '9"', depth: '5"', drop: '16"' },
  },
  {
    id: "1885896",
    slug: "prada-saffiano-re-edition-2005-shoulder-bag-white-1885896",
    brand: "Prada",
    name: "Saffiano Re-Edition 2005 Shoulder Bag White",
    price: 1750,
    estRetail: 2300,
    savingsPercent: 24,
    condition: "Excellent",
    color: "White",
    material: "Leather",
    bagType: "Shoulder Bags",
    images: [
      "https://cdn.shopify.com/s/files/1/0894/3186/7695/files/7e39d6fc90c4bcc1a92de0e57220821c.jpg?v=1779895209",
      "https://cdn.shopify.com/s/files/1/0894/3186/7695/files/15f5ad8e6a268da9b8b85d918615dddb.jpg?v=1779895209",
    ],
    description:
      "This is an authentic PRADA Saffiano Re-Edition 2005 Shoulder Bag in White. Crafted of Prada's signature Saffiano cross-grain leather in crisp white, this re-issue of the 2005 mini-hobo features a half-moon silhouette, removable chain-and-leather shoulder strap, and a zip top closure. The Prada triangle logo is set at the front. A contemporary icon.",
    itemNumber: "1885896",
    exterior: "Minor surface wear, light scuffs at base",
    hardware: "Light marks on silver-tone hardware",
    interior: "Clean Saffiano leather lining",
    comesWith: "Museum Grades Certificate of Authenticity, chain strap, dust bag",
    size: { base: '8"', height: '6"', depth: '3"', drop: '20"' },
  },
  {
    id: "1881850",
    slug: "prada-nappa-soft-padded-mini-triangle-crossbody-pouch-black-1881850",
    brand: "Prada",
    name: "Nappa Soft Padded Mini Triangle Crossbody Pouch Black",
    price: 1095,
    estRetail: 1600,
    savingsPercent: 32,
    condition: "Excellent",
    color: "Black",
    material: "Leather",
    bagType: "Crossbody Bags",
    images: [
      "https://cdn.shopify.com/s/files/1/0894/3186/7695/files/6facd8bcc8ef190f14199cc077f288cb.jpg?v=1779891231",
      "https://cdn.shopify.com/s/files/1/0894/3186/7695/files/1ee6fa3bd38f582f83323a0a5396f8b6.jpg?v=1779891231",
    ],
    description:
      "This is an authentic PRADA Nappa Soft Padded Mini Triangle Crossbody Pouch in Black. Crafted of padded nappa leather in black — soft, supple, and three-dimensionally puffed — this triangular mini pouch features a fine chain strap, a signature Prada triangle logo at the front, and a zip top closure. A compact, modern shape that nods to Prada's constructivist aesthetic.",
    itemNumber: "1881850",
    exterior: "Minor surface wear consistent with careful use",
    hardware: "Light marks on silver-tone hardware",
    interior: "Clean leather lining",
    comesWith: "Museum Grades Certificate of Authenticity, chain strap, dust bag",
    size: { base: '7"', height: '5"', depth: '2"', drop: '21"' },
  },
  {
    id: "1888586",
    slug: "prada-soft-calfskin-medium-darling-shoulder-bag-white-1888586",
    brand: "Prada",
    name: "Soft Calfskin Medium Darling Shoulder Bag White",
    price: 2395,
    estRetail: 3200,
    savingsPercent: 25,
    condition: "Excellent",
    color: "White",
    material: "Leather",
    bagType: "Shoulder Bags",
    images: [
      "https://cdn.shopify.com/s/files/1/0894/3186/7695/files/913d90a63c955e4f139fe0894987e738.jpg?v=1779557155",
      "https://cdn.shopify.com/s/files/1/0894/3186/7695/files/5b23acd852cb5602aecdb35c10e79455.jpg?v=1779557155",
    ],
    description:
      "This is an authentic PRADA Soft Calfskin Medium Darling Shoulder Bag in White. Crafted of smooth soft calfskin leather in crisp white, this structured shoulder bag features tall leather top handles, an optional leather crossbody strap, and a polished turn-lock closure. The Darling's clean architectural form reflects Prada's signature minimalist rigour.",
    itemNumber: "1888586",
    exterior: "Minor surface wear consistent with careful use",
    hardware: "Light marks on gold-tone hardware",
    interior: "Clean leather lining",
    comesWith: "Museum Grades Certificate of Authenticity, shoulder strap, dust bag",
    size: { base: '11"', height: '8.5"', depth: '4"', drop: '8"' },
  },
  {
    id: "1888350",
    slug: "prada-saffiano-lux-micro-galleria-double-zip-tote-fuxia-1888350",
    brand: "Prada",
    name: "Saffiano Lux Micro Galleria Double Zip Tote Fuxia",
    price: 950,
    estRetail: 1490,
    savingsPercent: 36,
    condition: "Excellent",
    color: "Pink",
    material: "Leather",
    bagType: "Totes",
    images: [
      "https://cdn.shopify.com/s/files/1/0894/3186/7695/files/22c563c47f11a2d4887c456957d667bd.jpg?v=1779557052",
      "https://cdn.shopify.com/s/files/1/0894/3186/7695/files/c1cc585cf73c291d54cb79a074c0523f.jpg?v=1779557052",
    ],
    description:
      "This is an authentic PRADA Saffiano Lux Micro Galleria Double Zip Tote in Fuxia. Crafted of cross-grain Saffiano patent leather in a bold fuchsia pink, this miniature version of the iconic Galleria features two zip compartments, rolled leather top handles, and the signature Prada triangle logo. Compact, colourful, and instantly recognisable.",
    itemNumber: "1888350",
    exterior: "Minor surface wear consistent with careful use",
    hardware: "Light marks on gold-tone hardware",
    interior: "Clean Saffiano leather lining",
    comesWith: "Museum Grades Certificate of Authenticity, dust bag",
    size: { base: '7"', height: '5"', depth: '2"', drop: '5"' },
  },
  {
    id: "1886460",
    slug: "prada-re-nylon-saffiano-belt-bag-black-1886460",
    brand: "Prada",
    name: "Re-Nylon Saffiano Belt Bag Black",
    price: 925,
    estRetail: 1390,
    savingsPercent: 33,
    condition: "Excellent",
    color: "Black",
    material: "Nylon",
    bagType: "Belt Bags",
    images: [
      "https://cdn.shopify.com/s/files/1/0894/3186/7695/files/74bc032d3baeacf660cb76aae44dc80d.jpg?v=1779556457",
      "https://cdn.shopify.com/s/files/1/0894/3186/7695/files/88c119ea78103f4484382cc63337665a.jpg?v=1779556457",
    ],
    description:
      "This is an authentic PRADA Re-Nylon Saffiano Belt Bag in Black. Crafted of Prada's Re-Nylon — a recycled nylon made from reclaimed ocean plastic and landfill waste — with Saffiano leather trim in black. Features a zip top closure, the iconic Prada triangle logo, and a wide adjustable belt strap. Functional, minimal, and made with Prada's sustainability credentials.",
    itemNumber: "1886460",
    exterior: "Minor surface wear consistent with use",
    hardware: "Light marks on silver-tone hardware",
    interior: "Clean nylon lining",
    comesWith: "Museum Grades Certificate of Authenticity, belt strap, dust bag",
    size: { base: '9"', height: '5.5"', depth: '2"', drop: '—' },
  },
  {
    id: "1884999",
    slug: "prada-nylon-re-edition-2005-shoulder-bag-black-1884999",
    brand: "Prada",
    name: "Nylon Re-Edition 2005 Shoulder Bag Black",
    price: 1595,
    estRetail: 2200,
    savingsPercent: 27,
    condition: "Excellent",
    color: "Black",
    material: "Nylon",
    bagType: "Shoulder Bags",
    images: [
      "https://cdn.shopify.com/s/files/1/0894/3186/7695/files/daa951deb51773e611afabac76813cb8.jpg?v=1779876296",
      "https://cdn.shopify.com/s/files/1/0894/3186/7695/files/3c9d512d9a665c2b0f55732cae86118c.jpg?v=1779876306",
    ],
    description:
      "This is an authentic PRADA Nylon Re-Edition 2005 Shoulder Bag in Black. Crafted of Prada's signature tessuto nylon in black with Saffiano leather trim, this re-issue of the house's archival 2005 hobo features a half-moon silhouette, removable chain-and-nylon shoulder strap, and a zip top closure. The Prada triangle logo is set proudly at the front.",
    itemNumber: "1884999",
    exterior: "Minor surface wear consistent with careful use",
    hardware: "Light marks on silver-tone hardware",
    interior: "Clean nylon lining",
    comesWith: "Museum Grades Certificate of Authenticity, chain strap, dust bag",
    size: { base: '8"', height: '6"', depth: '3"', drop: '20"' },
  },
  {
    id: "1887305",
    slug: "prada-city-calfskin-saffiano-cahier-bag-fuoco-black-1887305",
    brand: "Prada",
    name: "City Calfskin Saffiano Cahier Bag Fuoco Black",
    price: 1195,
    estRetail: 1890,
    savingsPercent: 37,
    condition: "Excellent",
    color: "Red",
    material: "Leather",
    bagType: "Shoulder Bags",
    images: [
      "https://cdn.shopify.com/s/files/1/0894/3186/7695/files/fec660de94f40193ddfb1916a8c501a2.jpg?v=1779876160",
      "https://cdn.shopify.com/s/files/1/0894/3186/7695/files/518a1d396e94ec4b4ad467598101e81c.jpg?v=1779876160",
    ],
    description:
      "This is an authentic PRADA City Calfskin Saffiano Cahier Bag in Fuoco and Black. Crafted of smooth city calfskin in fiery red (Fuoco) with Saffiano leather trim in black — a bold, contrasting two-tone combination. The Cahier's structured book-like form features a flap with turn-lock closure, a chain shoulder strap with leather pad, and gold-tone hardware throughout.",
    itemNumber: "1887305",
    exterior: "Minor surface wear consistent with careful use",
    hardware: "Light marks on gold-tone hardware",
    interior: "Clean leather lining",
    comesWith: "Museum Grades Certificate of Authenticity, chain strap, dust bag",
    size: { base: '9"', height: '7"', depth: '2.5"', drop: '19"' },
  },
  {
    id: "1885461",
    slug: "prada-saffiano-lux-large-double-zip-tote-fuoco-1885461",
    brand: "Prada",
    name: "Saffiano Lux Large Double Zip Tote Fuoco",
    price: 1005,
    estRetail: 1750,
    savingsPercent: 43,
    condition: "Excellent",
    color: "Red",
    material: "Leather",
    bagType: "Totes",
    images: [
      "https://cdn.shopify.com/s/files/1/0894/3186/7695/files/cec685020124cf52e55e395391343751.jpg?v=1779545522",
      "https://cdn.shopify.com/s/files/1/0894/3186/7695/files/dd3893b5fe3b08bbb0c68e332cf0693e.jpg?v=1779545522",
    ],
    description:
      "This is an authentic PRADA Saffiano Lux Large Double Zip Tote in Fuoco. Crafted of Prada's signature cross-grain Saffiano leather in fiery red, this large structured tote is a wardrobe staple. Features two zip compartments offering excellent organisation, rolled leather top handles, and the iconic Prada triangle logo. A bold, versatile piece for everyday luxury.",
    itemNumber: "1885461",
    exterior: "Minor corner wear consistent with careful use",
    hardware: "Light marks on gold-tone hardware",
    interior: "Clean Saffiano leather lining",
    comesWith: "Museum Grades Certificate of Authenticity, dust bag",
    size: { base: '15"', height: '11"', depth: '6"', drop: '6"' },
  },

  // ── GUCCI ────────────────────────────────────────────────────────────────────

  {
    id: "1583625",
    slug: "gucci-microguccissima-medium-joy-boston-soft-pink-1583625",
    brand: "Gucci",
    name: "Microguccissima Medium Joy Boston Soft Pink",
    price: 1095,
    estRetail: 1980,
    savingsPercent: 45,
    condition: "Excellent",
    color: "Pink",
    material: "Leather",
    bagType: "Handbags",
    images: [
      "https://cdn.shopify.com/s/files/1/0894/3186/7695/files/382e42915b7b27801b2e4e9c98029729.jpg?v=1768723341",
      "https://cdn.shopify.com/s/files/1/0894/3186/7695/files/dd5e9c5c435096a3afa3d90d17981fcd.jpg?v=1768723341",
    ],
    description:
      "This is an authentic GUCCI Microguccissima Medium Joy Boston in Soft Pink. Crafted of Microguccissima-embossed leather in light pink — a fine, all-over micro GG monogram pressed into the leather for subtle texture — this Boston bag features rolled leather top handles, an optional shoulder strap, and gold-tone interlocking G hardware. A feminine and collectible Gucci silhouette.",
    itemNumber: "1583625",
    exterior: "Minor surface wear consistent with careful use",
    hardware: "Light marks on gold-tone hardware",
    interior: "Clean microfibre lining",
    comesWith: "Museum Grades Certificate of Authenticity, shoulder strap, dust bag",
    size: { base: '12"', height: '8"', depth: '6"', drop: '4"' },
  },
  {
    id: "1696465",
    slug: "gucci-gg-supreme-monogram-mini-dionysus-shoulder-bag-taupe-1696465",
    brand: "Gucci",
    name: "GG Supreme Monogram Mini Dionysus Shoulder Bag Taupe",
    price: 920,
    estRetail: 1450,
    savingsPercent: 37,
    condition: "Excellent",
    color: "Beige",
    material: "Canvas",
    bagType: "Shoulder Bags",
    images: [
      "https://cdn.shopify.com/s/files/1/0894/3186/7695/files/fde886bb1c2baeecc9085154f5a278d5_a94a4493-6a30-46a0-94be-b0b6f133e104.jpg?v=1767860486",
      "https://cdn.shopify.com/s/files/1/0894/3186/7695/files/5d8856d988149724a45478f6fa4a71df_b9749c84-225e-4e0f-ad4d-a679cb6a6d18.jpg?v=1767860486",
    ],
    description:
      "This is an authentic GUCCI GG Supreme Monogram Mini Dionysus Shoulder Bag in Taupe. Crafted of the house's iconic GG Supreme monogram coated canvas in brown on beige, this petite Dionysus features an aged silver chain strap and the signature tiger-head closure — a motif drawn from Gucci's equestrian heritage. Interior in suede with a zip pocket.",
    itemNumber: "1696465",
    exterior: "Minor surface wear at base corners",
    hardware: "Light scratches on aged silver-tone tiger-head closure",
    interior: "Clean suede lining",
    comesWith: "Museum Grades Certificate of Authenticity, chain strap, dust bag",
    size: { base: '7"', height: '5.5"', depth: '3"', drop: '20"' },
  },
  {
    id: "1683129",
    slug: "gucci-calfskin-gg-matelasse-mini-top-handle-bag-rhodamine-pink-1683129",
    brand: "Gucci",
    name: "Calfskin GG Matelasse Mini Top Handle Bag Rhodamine Pink",
    price: 1480,
    estRetail: 2200,
    savingsPercent: 33,
    condition: "Excellent",
    color: "Pink",
    material: "Leather",
    bagType: "Handbags",
    images: [
      "https://cdn.shopify.com/s/files/1/0894/3186/7695/files/51159602ee32b0d5d874e8d74c94d2e4.jpg?v=1768377829",
      "https://cdn.shopify.com/s/files/1/0894/3186/7695/files/dab4d34d6e919ff3776256418e8f19ad.jpg?v=1768377839",
    ],
    description:
      "This is an authentic GUCCI Calfskin GG Matelasse Mini Top Handle Bag in Rhodamine Pink. Crafted of pink calfskin leather with an all-over matelassé GG quilting pattern, this structured mini top handle bag features polished gold hardware, a flat leather top handle, and an optional shoulder strap. A rare and striking colourway of one of Gucci's most refined contemporary shapes.",
    itemNumber: "1683129",
    exterior: "Minor surface wear consistent with careful use",
    hardware: "Light marks on gold-tone hardware",
    interior: "Clean microfibre lining",
    comesWith: "Museum Grades Certificate of Authenticity, shoulder strap, dust bag",
    size: { base: '8"', height: '5.5"', depth: '3.5"', drop: '3"' },
  },
  {
    id: "1714739",
    slug: "gucci-metallic-calfskin-medium-new-bamboo-top-handle-bag-bronze-1714739",
    brand: "Gucci",
    name: "Metallic Calfskin Medium New Bamboo Top Handle Bag Bronze",
    price: 1150,
    estRetail: 2150,
    savingsPercent: 47,
    condition: "Excellent",
    color: "Brown",
    material: "Leather",
    bagType: "Handbags",
    images: [
      "https://cdn.shopify.com/s/files/1/0894/3186/7695/files/d8b2e79e995e14a41fcd01f9d3058270.jpg?v=1766416599",
      "https://cdn.shopify.com/s/files/1/0894/3186/7695/files/7492bdd8f0a65b0cffafd9c9cf59da5f.jpg?v=1766416609",
    ],
    description:
      "This is an authentic GUCCI Metallic Calfskin Medium New Bamboo Top Handle Bag in Bronze. Crafted of metallic calfskin leather in a warm bronze with a looping lacquered bamboo top handle — an homage to the house's 1947 original — and an optional crossbody strap. Gold-tone hardware. The bamboo handle is one of Gucci's most iconic archival details.",
    itemNumber: "1714739",
    exterior: "Minor surface wear consistent with careful use",
    hardware: "Light marks on gold-tone hardware; bamboo handle in excellent condition",
    interior: "Clean microfibre lining",
    comesWith: "Museum Grades Certificate of Authenticity, crossbody strap, dust bag",
    size: { base: '12"', height: '8.5"', depth: '5.5"', drop: '3.5"' },
  },
  {
    id: "1714340",
    slug: "gucci-pony-hair-new-bamboo-medium-top-handle-bag-black-1714340",
    brand: "Gucci",
    name: "Pony Hair New Bamboo Medium Top Handle Bag Black",
    price: 1790,
    estRetail: 2800,
    savingsPercent: 36,
    condition: "Excellent",
    color: "Black",
    material: "Leather",
    bagType: "Handbags",
    images: [
      "https://cdn.shopify.com/s/files/1/0894/3186/7695/files/ed006a6013992a54ade4757ee85da1a5.jpg?v=1764849213",
      "https://cdn.shopify.com/s/files/1/0894/3186/7695/files/eb275e01f68097a4f0932b76d7aed004.jpg?v=1764849214",
    ],
    description:
      "This is an authentic GUCCI Pony Hair New Bamboo Medium Top Handle Bag in Black. Crafted of rich black pony hair with a looping lacquered bamboo top handle and an optional crossbody strap. The textural contrast between the tactile pony hair body and the polished bamboo is both distinctive and luxurious. Gold-tone hardware throughout. A bold, collectible Gucci piece.",
    itemNumber: "1714340",
    exterior: "Pony hair in excellent condition, minor wear on leather trim",
    hardware: "Light marks on gold-tone hardware; bamboo handle in excellent condition",
    interior: "Clean microfibre lining",
    comesWith: "Museum Grades Certificate of Authenticity, crossbody strap, dust bag",
    size: { base: '12"', height: '8.5"', depth: '5.5"', drop: '3.5"' },
  },
  {
    id: "1741244",
    slug: "gucci-calfskin-smilla-shoulder-bag-winter-leaf-1741244",
    brand: "Gucci",
    name: "Calfskin Smilla Shoulder Bag Winter Leaf",
    price: 1000,
    estRetail: 1650,
    savingsPercent: 39,
    condition: "Excellent",
    color: "Green",
    material: "Leather",
    bagType: "Shoulder Bags",
    images: [
      "https://cdn.shopify.com/s/files/1/0894/3186/7695/files/fc61dc553e68cc1e85a341e8112de82e.jpg?v=1768199693",
      "https://cdn.shopify.com/s/files/1/0894/3186/7695/files/0ab53abcb0bbaee1d5ed64b3b72e3620.jpg?v=1768199693",
    ],
    description:
      "This is an authentic GUCCI Calfskin Smilla Shoulder Bag in Winter Leaf. Crafted of smooth calfskin leather in a deep forest green (Winter Leaf), the Smilla features the interlocking G hardware closure at the front, a shoulder strap, and clean architectural lines. A refined, minimal shape that carries Gucci's equestrian-inspired hardware with restrained elegance.",
    itemNumber: "1741244",
    exterior: "Minor surface wear consistent with careful use",
    hardware: "Light marks on gold-tone interlocking G hardware",
    interior: "Clean microfibre lining",
    comesWith: "Museum Grades Certificate of Authenticity, shoulder strap, dust bag",
    size: { base: '10"', height: '7"', depth: '3"', drop: '19"' },
  },
  {
    id: "1750196",
    slug: "gucci-dollar-calfskin-crystal-mini-dionysus-top-handle-bag-emerald-1750196",
    brand: "Gucci",
    name: "Dollar Calfskin Crystal Mini Dionysus Top Handle Bag Emerald",
    price: 1465,
    estRetail: 2400,
    savingsPercent: 39,
    condition: "Excellent",
    color: "Green",
    material: "Leather",
    bagType: "Handbags",
    images: [
      "https://cdn.shopify.com/s/files/1/0894/3186/7695/files/14df19390419e1dfa666ecb0375d5ba7.jpg?v=1768458761",
      "https://cdn.shopify.com/s/files/1/0894/3186/7695/files/0683099807f7afe906db71c652799088.jpg?v=1768458771",
    ],
    description:
      "This is an authentic GUCCI Dollar Calfskin Crystal Mini Dionysus Top Handle Bag in Emerald. Crafted of textured dollar calfskin in a vivid emerald green, this petite Dionysus features a crystal-encrusted tiger-head closure — an extraordinary embellishment on one of Gucci's most emblematic silhouettes. Features a flat leather top handle and optional crossbody strap.",
    itemNumber: "1750196",
    exterior: "Minor surface wear consistent with careful use; crystals complete and secure",
    hardware: "Light marks on gold-tone hardware",
    interior: "Clean microfibre lining",
    comesWith: "Museum Grades Certificate of Authenticity, crossbody strap, dust bag",
    size: { base: '7"', height: '5.5"', depth: '3.5"', drop: '3"' },
  },
  {
    id: "1763479",
    slug: "gucci-calfskin-mini-moon-side-shoulder-bag-black-1763479",
    brand: "Gucci",
    name: "Calfskin Mini Moon Side Shoulder Bag Black",
    price: 1265,
    estRetail: 1980,
    savingsPercent: 36,
    condition: "Excellent",
    color: "Black",
    material: "Leather",
    bagType: "Shoulder Bags",
    images: [
      "https://cdn.shopify.com/s/files/1/0894/3186/7695/files/9a7405f7b8e7f1fdcf70e4ac04d21e40.jpg?v=1764846572",
      "https://cdn.shopify.com/s/files/1/0894/3186/7695/files/abea66a9d7be04806e4a428cb9ceaabb.jpg?v=1764846572",
    ],
    description:
      "This is an authentic GUCCI Calfskin Mini Moon Side Shoulder Bag in Black. Crafted of smooth black calfskin leather, this crescent-shaped mini shoulder bag features a distinctive curved silhouette, a zip top closure, and polished gold-tone hardware. The Moon Side's sculptural form makes it one of Gucci's most architecturally distinctive recent designs.",
    itemNumber: "1763479",
    exterior: "Minor surface wear consistent with careful use",
    hardware: "Light marks on gold-tone hardware",
    interior: "Clean microfibre lining",
    comesWith: "Museum Grades Certificate of Authenticity, shoulder strap, dust bag",
    size: { base: '7"', height: '5"', depth: '3"', drop: '20"' },
  },
  {
    id: "1753546",
    slug: "gucci-gg-supreme-ophidia-super-mini-bowler-bag-beige-ebony-1753546",
    brand: "Gucci",
    name: "GG Supreme Ophidia Super Mini Bowler Bag Beige Ebony New Acero",
    price: 1465,
    estRetail: 1980,
    savingsPercent: 26,
    condition: "Excellent",
    color: "Beige",
    material: "Canvas",
    bagType: "Handbags",
    images: [
      "https://cdn.shopify.com/s/files/1/0894/3186/7695/files/546e80581ab661b03f98ca48daaa94c0.jpg?v=1764933799",
      "https://cdn.shopify.com/s/files/1/0894/3186/7695/files/bda7ae5b666dab94964049450d519871.jpg?v=1764933799",
    ],
    description:
      "This is an authentic GUCCI GG Supreme Monogram Ophidia Super Mini Bowler Bag in Beige Ebony and New Acero. Crafted of the house's GG Supreme coated canvas in brown on beige with New Acero web stripe and textured dollar calfskin leather trim. The super mini bowler features a top handle, an optional crossbody strap, and the Web-detailed D-ring closure.",
    itemNumber: "1753546",
    exterior: "Minor surface wear at base corners",
    hardware: "Light marks on gold-tone hardware",
    interior: "Clean microfibre lining",
    comesWith: "Museum Grades Certificate of Authenticity, crossbody strap, dust bag",
    size: { base: '8"', height: '6.5"', depth: '4"', drop: '3.5"' },
  },
  {
    id: "1890335",
    slug: "gucci-gg-supreme-ophidia-small-crossbody-bag-beige-ebony-1890335",
    brand: "Gucci",
    name: "GG Supreme Monogram Ophidia Small Crossbody Bag Beige Ebony Fuchsia",
    price: 1395,
    estRetail: 1980,
    savingsPercent: 30,
    condition: "Excellent",
    color: "Beige",
    material: "Canvas",
    bagType: "Crossbody Bags",
    images: [
      "https://cdn.shopify.com/s/files/1/0894/3186/7695/files/7783365ec873f3c38e2252e3a9e6c452.jpg?v=1779558339",
    ],
    description:
      "This is an authentic GUCCI GG Supreme Monogram Ophidia Small Crossbody Bag in Beige Ebony Fuchsia. Crafted of the house's iconic GG Supreme canvas in brown on beige with a fuchsia web stripe and textured dollar calfskin leather trim. Features a gold-tone interlocking G closure and an adjustable leather crossbody strap.",
    itemNumber: "1890335",
    exterior: "Minor surface wear at base corners",
    hardware: "Light scratches on gold-tone interlocking G hardware",
    interior: "Clean microfibre lining",
    comesWith: "Museum Grades Certificate of Authenticity, adjustable strap, dust bag",
    size: { base: '9"', height: '6"', depth: '3"', drop: '23"' },
  },
];

export const seedCategories = [
  { name: "Crossbody",     image: "/images/cat-crossbody.jpg",  href: "/collections/all-bags?bagType=Crossbody+Bags" },
  { name: "Totes",         image: "/images/cat-totes.jpg",      href: "/collections/all-bags?bagType=Totes" },
  { name: "Shoulder Bags", image: "/images/cat-shoulder.jpg",   href: "/collections/all-bags?bagType=Shoulder+Bags" },
  { name: "Backpacks",     image: "/images/cat-backpacks.jpg",  href: "/collections/all-bags?bagType=Backpacks" },
  { name: "Belt Bags",     image: "/images/cat-belt.jpg",       href: "/collections/all-bags?bagType=Belt+Bags" },
  { name: "Hobo Bags",     image: "/images/cat-hobo.jpg",       href: "/collections/all-bags?bagType=Hobo+Bags" },
  { name: "Bucket Bags",   image: "/images/cat-bucket.jpg",     href: "/collections/all-bags?bagType=Bucket+Bags" },
  { name: "Clutches",      image: "/images/cat-clutches.jpg",   href: "/collections/all-bags?bagType=Clutches" },
  { name: "Satchels",      image: "/images/cat-satchels.jpg",   href: "/collections/all-bags?bagType=Satchels" },
];
