import type { Product } from "@/types/product";

export const seedProducts: Product[] = [
  {
    id: "1892213",
    slug: "chanel-lambskin-mini-pearl-crush-flap-dark-grey-1892213",
    brand: "Chanel",
    name: "Lambskin Mini Pearl Crush Rectangular Flap Dark Grey",
    price: 5395,
    estRetail: 7200,
    savingsPercent: 25,
    condition: "Excellent",
    color: "Grey",
    material: "Leather",
    bagType: "Crossbody Bags",
    images: [
      "https://cdn.shopify.com/s/files/1/0894/3186/7695/files/762f25b75ef7a6c0ba626e6fc8bf39a6_ad243b85-721b-44fa-9425-a169342f9df2.jpg?v=1779645023",
    ],
    description:
      "This is an authentic CHANEL Lambskin Quilted CC Pearl Crush Mini Rectangular Flap in Dark Grey. Crafted in soft quilted lambskin leather in dark grey, this coveted design features the signature gold CC turn-lock closure and a gold chain-link leather-threaded shoulder strap. The Pearl Crush collection adds a distinctive pearlised texture to Chanel's classic quilting, creating an interplay of light unique to this series.",
    itemNumber: "1892213",
    exterior: "Minor surface scuffs consistent with careful use",
    hardware: "Light surface scratches on gold-tone hardware",
    interior: "Clean leather lining, no marks or odour",
    comesWith:
      "Museum Grades Certificate of Authenticity, chain strap, dust bag",
    size: { base: '5.5"', height: '3.5"', depth: '2"', drop: '21"' },
  },
  {
    id: "1890767",
    slug: "chanel-caviar-quilted-petit-timeless-tote-ptt-black-1890767",
    brand: "Chanel",
    name: "Caviar Quilted Petit Timeless Tote PTT Black",
    price: 2495,
    estRetail: 3900,
    savingsPercent: 36,
    condition: "Excellent",
    color: "Black",
    material: "Leather",
    bagType: "Totes",
    images: [
      "https://cdn.shopify.com/s/files/1/0894/3186/7695/files/59bc6a9eaf6abd6de7e339794d992b29.jpg?v=1779558374",
    ],
    description:
      "This is an authentic CHANEL Caviar Quilted Petit Timeless Tote PTT in Black. Crafted of luxurious diamond quilted caviar leather in black, this compact tote is one of Chanel's most practical and enduring silhouettes. Features a gold-tone interlocking CC push-lock closure, woven chain and leather handles, and a spacious interior with zip and patch pockets.",
    itemNumber: "1890767",
    exterior: "Minor corner wear consistent with careful use",
    hardware: "Light wear on gold-tone hardware",
    interior: "Clean burgundy leather lining",
    comesWith:
      "Museum Grades Certificate of Authenticity, dust bag",
    size: { base: '12"', height: '8.5"', depth: '4.5"', drop: '9"' },
  },
  {
    id: "1890410",
    slug: "balenciaga-chevre-silver-metallic-edge-hardware-mini-city-bleu-de-minuit-1890410",
    brand: "Balenciaga",
    name: "Chevre Silver Metallic Edge Hardware Mini City Bleu de Minuit",
    price: 1695,
    estRetail: 2350,
    savingsPercent: 28,
    condition: "Excellent",
    color: "Blue",
    material: "Leather",
    bagType: "Crossbody Bags",
    images: [
      "https://cdn.shopify.com/s/files/1/0894/3186/7695/files/cc47fc9cba37e62d8720f6635fe78427.jpg?v=1779558364",
    ],
    description:
      "This is an authentic BALENCIAGA Chevre Silver Metallic Edge Hardware Mini City in Bleu de Minuit. Crafted of richly textured chèvre goatskin leather in a deep navy blue, this rare variant features silver metallic edge-painted hardware — a limited detail that elevates the City's iconic silhouette. Includes the signature studded base, zip top, and a removable adjustable crossbody strap.",
    itemNumber: "1890410",
    exterior: "Minor surface wear on leather edges",
    hardware: "Light wear on silver-tone metallic edge hardware",
    interior: "Clean canvas lining",
    comesWith:
      "Museum Grades Certificate of Authenticity, adjustable strap, dust bag",
    size: { base: '9.5"', height: '6"', depth: '5"', drop: '22"' },
  },
  {
    id: "1890335",
    slug: "gucci-gg-supreme-ophidia-small-crossbody-bag-beige-ebony-1890335",
    brand: "Gucci",
    name: "GG Supreme Monogram Ophidia Small Crossbody Bag Beige Ebony Fuchsia",
    price: 1395,
    estRetail: 1980,
    savingsPercent: 30,
    condition: "Excellent",
    color: "Beige",
    material: "Canvas",
    bagType: "Crossbody Bags",
    images: [
      "https://cdn.shopify.com/s/files/1/0894/3186/7695/files/7783365ec873f3c38e2252e3a9e6c452.jpg?v=1779558339",
    ],
    description:
      "This is an authentic GUCCI GG Supreme Monogram Textured Dollar Calfskin Web Ophidia Small Crossbody Bag in Beige Ebony Fuchsia. Crafted of the house's iconic brown on beige GG Supreme canvas with a fuchsia web stripe detail and textured dollar calfskin leather trim. Features a gold-tone interlocking G closure and an adjustable leather crossbody strap.",
    itemNumber: "1890335",
    exterior: "Minor surface wear at base corners",
    hardware: "Light scratches on gold-tone interlocking G hardware",
    interior: "Clean microfibre lining",
    comesWith:
      "Museum Grades Certificate of Authenticity, adjustable strap, dust bag",
    size: { base: '9"', height: '6"', depth: '3"', drop: '23"' },
  },
  {
    id: "1890276",
    slug: "chloe-calfskin-medium-marcie-round-crossbody-bag-tan-1890276",
    brand: "Chloé",
    name: "Calfskin Medium Marcie Round Crossbody Bag Tan",
    price: 1250,
    estRetail: 1850,
    savingsPercent: 32,
    condition: "Excellent",
    color: "Tan",
    material: "Leather",
    bagType: "Crossbody Bags",
    images: [
      "https://cdn.shopify.com/s/files/1/0894/3186/7695/files/acf6df85cf5591fa323ac2430a5c42ba.jpg?v=1779558330",
    ],
    description:
      "This is an authentic CHLOÉ Calfskin Medium Marcie Round Crossbody Bag in Tan. Crafted of grained calfskin leather in warm brown, the Marcie's signature round silhouette is defined by its hand-stitched saddle-stitch detailing and a large brass toggle closure. The adjustable calfskin crossbody strap completes this relaxed yet refined piece.",
    itemNumber: "1890276",
    exterior: "Minor surface wear, light scuffs on edges",
    hardware: "Light patina on brass-tone toggle closure",
    interior: "Clean suede lining",
    comesWith:
      "Museum Grades Certificate of Authenticity, adjustable strap, dust bag",
    size: { base: '9"', height: '9"', depth: '3"', drop: '24"' },
  },
];

export const seedCategories = [
  { name: "Crossbody",     image: "/images/cat-crossbody.jpg",  href: "/collections/all-bags?bagType=Crossbody+Bags" },
  { name: "Totes",         image: "/images/cat-totes.jpg",      href: "/collections/all-bags?bagType=Totes" },
  { name: "Shoulder Bags", image: "/images/cat-shoulder.jpg",   href: "/collections/all-bags?bagType=Shoulder+Bags" },
  { name: "Backpacks",     image: "/images/cat-backpacks.jpg",  href: "/collections/all-bags?bagType=Backpacks" },
  { name: "Belt Bags",     image: "/images/cat-belt.jpg",       href: "/collections/all-bags?bagType=Belt+Bags" },
  { name: "Hobo Bags",     image: "/images/cat-hobo.jpg",       href: "/collections/all-bags?bagType=Hobo+Bags" },
  { name: "Bucket Bags",   image: "/images/cat-bucket.jpg",     href: "/collections/all-bags?bagType=Bucket+Bags" },
  { name: "Clutches",      image: "/images/cat-clutches.jpg",   href: "/collections/all-bags?bagType=Clutches" },
  { name: "Satchels",      image: "/images/cat-satchels.jpg",   href: "/collections/all-bags?bagType=Satchels" },
];
