import type { Product } from "@/types/product";

export const seedProducts: Product[] = [
  {
    id: "1823265",
    slug: "gucci-roxy-calfskin-blondie-chain-shoulder-flap-bag-powder-pink-1823265",
    brand: "Gucci",
    name: "Roxy Calfskin Blondie Chain Shoulder Flap Bag Powder Pink",
    price: 1430,
    estRetail: 3600,
    savingsPercent: 60,
    condition: "Excellent",
    color: "Pink",
    material: "Leather",
    bagType: "Shoulder Bags",
    images: [
      "/images/products/gucci-blondie-1.jpg",
      "/images/products/gucci-blondie-2.jpg",
    ],
    description:
      "This is an authentic GUCCI Roxy Calfskin Blondie Chain Shoulder Flap Bag in Powder Pink. This stylish baguette is crafted of luxurious pink smooth calfskin leather. It features a gold chain strap, an adjustable leather shoulder strap with gold links, and a prominent brass Gucci interlocking GG logo at the front. The front flap opens to a matching leather interior with a zipper pocket.",
    itemNumber: "1823265",
    exterior: "Edge wear, imprints, faint scuffs, surface wear",
    hardware: "Scratch(es)",
    interior: "Surface wear, marks, imprints",
    comesWith: "Museum Grades Certificate of Authenticity, strap, chain strap",
    size: { base: '11"', height: '7"', depth: '2.75"', drop: '13"' },
  },
  {
    id: "1834521",
    slug: "chanel-caviar-quilted-wallet-on-chain-woc-beige-1834521",
    brand: "Chanel",
    name: "Caviar Quilted Wallet on Chain WOC Beige",
    price: 4610,
    estRetail: 3900,
    savingsPercent: 0,
    condition: "Excellent",
    color: "Beige",
    material: "Leather",
    bagType: "Crossbody Bags",
    images: ["/images/products/chanel-woc-1.jpg"],
    description:
      "This is an authentic CHANEL Caviar Quilted Wallet on Chain WOC in Beige. This elegant wallet on chain is crafted of diamond quilted caviar leather in beige.",
    itemNumber: "1834521",
    exterior: "Minor surface wear",
    hardware: "Light scratch(es)",
    interior: "Clean",
    comesWith: "Museum Grades Certificate of Authenticity, chain strap",
    size: { base: '7.5"', height: '5"', depth: '1.5"', drop: '24"' },
  },
  {
    id: "1812453",
    slug: "louis-vuitton-epi-kleber-mm-black-1812453",
    brand: "Louis Vuitton",
    name: "Epi Kleber MM Black",
    price: 1220,
    estRetail: 2550,
    savingsPercent: 52,
    condition: "Shows Wear",
    color: "Black",
    material: "Leather",
    bagType: "Totes",
    images: ["/images/products/lv-kleber-1.jpg"],
    description:
      "This is an authentic LOUIS VUITTON Epi Kleber MM in Black. This sophisticated handbag is crafted of Louis Vuitton Epi textured leather in black.",
    itemNumber: "1812453",
    exterior: "Corner wear, scuffs, marks",
    hardware: "Tarnishing, scratch(es)",
    interior: "Surface wear, marks",
    comesWith: "Museum Grades Certificate of Authenticity, strap",
    size: { base: '13"', height: '9.5"', depth: '6"', drop: '4"' },
  },
  {
    id: "1845672",
    slug: "louis-vuitton-monogram-multicolor-speedy-30-white-1845672",
    brand: "Louis Vuitton",
    name: "Monogram Multicolor Speedy 30 White",
    price: 2220,
    estRetail: 3150,
    savingsPercent: 30,
    condition: "Shows Wear",
    color: "White",
    material: "Canvas",
    bagType: "Handbags",
    images: ["/images/products/lv-speedy-1.jpg"],
    description:
      "This is an authentic LOUIS VUITTON Monogram Multicolor Speedy 30 in White. This iconic handbag features the colorful Louis Vuitton monogram on white Toile canvas.",
    itemNumber: "1845672",
    exterior: "Patina, marks, light staining",
    hardware: "Tarnishing",
    interior: "Surface wear, marks",
    comesWith: "Museum Grades Certificate of Authenticity, lock, key, padlock",
    size: { base: '12"', height: '8.5"', depth: '7"', drop: '4"' },
  },
  {
    id: "1856321",
    slug: "celine-small-bucket-cuir-triomphe-tan-1856321",
    brand: "Celine",
    name: "Small Bucket Cuir Triomphe Tan",
    price: 1295,
    estRetail: 2350,
    savingsPercent: 45,
    condition: "Excellent",
    color: "Brown",
    material: "Leather",
    bagType: "Bucket Bags",
    images: ["/images/products/celine-bucket-1.jpg"],
    description:
      "This is an authentic CELINE Small Bucket Cuir Triomphe in Tan. Crafted from smooth calfskin leather with the Triomphe embossed pattern.",
    itemNumber: "1856321",
    exterior: "Minor surface wear",
    hardware: "Light scratch(es)",
    interior: "Clean, minor marks",
    comesWith: "Museum Grades Certificate of Authenticity, removable pouch",
    size: { base: '9"', height: '10"', depth: '5"', drop: '8"' },
  },
  {
    id: "1867432",
    slug: "chanel-lambskin-quilted-medium-chanel-19-red-1867432",
    brand: "Chanel",
    name: "Lambskin Quilted Medium Chanel 19 Red",
    price: 4950,
    estRetail: 5800,
    savingsPercent: 15,
    condition: "Excellent",
    color: "Red",
    material: "Leather",
    bagType: "Handbags",
    images: ["/images/products/chanel-19-1.jpg"],
    description:
      "This is an authentic CHANEL Lambskin Quilted Medium Chanel 19 in Red. This stunning flap bag is crafted of luxurious diamond quilted lambskin leather in vibrant red.",
    itemNumber: "1867432",
    exterior: "Faint surface wear",
    hardware: "Light scratch(es)",
    interior: "Clean",
    comesWith: "Museum Grades Certificate of Authenticity, chain strap, dust bag",
    size: { base: '10"', height: '6.5"', depth: '3.5"', drop: '11"' },
  },
  {
    id: "1878543",
    slug: "louis-vuitton-monogram-graceful-mm-pivoine-1878543",
    brand: "Louis Vuitton",
    name: "Monogram Graceful MM Pivoine",
    price: 1150,
    estRetail: 1980,
    savingsPercent: 42,
    condition: "Shows Wear",
    color: "Pink",
    material: "Canvas",
    bagType: "Shoulder Bags",
    images: ["/images/products/lv-graceful-1.jpg"],
    description:
      "This is an authentic LOUIS VUITTON Monogram Graceful MM in Pivoine. This hobo bag features the signature monogram canvas with a microfiber lining in pivoine pink.",
    itemNumber: "1878543",
    exterior: "Patina, water stains, marks",
    hardware: "Tarnishing",
    interior: "Surface wear, marks",
    comesWith: "Museum Grades Certificate of Authenticity",
    size: { base: '15"', height: '11"', depth: '4"', drop: '10"' },
  },
  {
    id: "1889654",
    slug: "gucci-gg-marmont-matelasse-small-shoulder-bag-black-1889654",
    brand: "Gucci",
    name: "GG Marmont Matelasse Small Shoulder Bag Black",
    price: 1680,
    estRetail: 2980,
    savingsPercent: 44,
    condition: "Excellent",
    color: "Black",
    material: "Leather",
    bagType: "Shoulder Bags",
    images: ["/images/products/gucci-marmont-1.jpg"],
    description:
      "This is an authentic GUCCI GG Marmont Matelasse Small Shoulder Bag in Black. This stylish shoulder bag is crafted of black chevron quilted leather.",
    itemNumber: "1889654",
    exterior: "Minor surface wear, faint scuffs",
    hardware: "Light scratch(es)",
    interior: "Clean",
    comesWith: "Museum Grades Certificate of Authenticity, strap",
    size: { base: '10"', height: '6"', depth: '3"', drop: '20"' },
  },
  {
    id: "1890765",
    slug: "hermes-togo-birkin-25-gold-1890765",
    brand: "Hermes",
    name: "Togo Birkin 25 Gold",
    price: 14500,
    estRetail: 12100,
    savingsPercent: 0,
    condition: "Excellent",
    color: "Brown",
    material: "Leather",
    bagType: "Handbags",
    images: ["/images/products/hermes-birkin-1.jpg"],
    description:
      "This is an authentic HERMES Togo Birkin 25 in Gold. This iconic Birkin bag is crafted of Hermes signature Togo grained calfskin leather in gold.",
    itemNumber: "1890765",
    exterior: "Minor corner wear",
    hardware: "Light scratch(es)",
    interior: "Clean",
    comesWith:
      "Museum Grades Certificate of Authenticity, lock, key, clochette, dust bag, rain cover, box",
    size: { base: '10"', height: '8"', depth: '5"', drop: '3.5"' },
  },
  {
    id: "1901876",
    slug: "prada-saffiano-lux-galleria-medium-nero-1901876",
    brand: "Prada",
    name: "Saffiano Lux Galleria Medium Nero",
    price: 1595,
    estRetail: 3250,
    savingsPercent: 51,
    condition: "Shows Wear",
    color: "Black",
    material: "Leather",
    bagType: "Handbags",
    images: ["/images/products/prada-galleria-1.jpg"],
    description:
      "This is an authentic PRADA Saffiano Lux Galleria Medium in Nero. This classic handbag is crafted of Prada Saffiano cross-grain leather in black.",
    itemNumber: "1901876",
    exterior: "Corner wear, scuffs",
    hardware: "Scratch(es), tarnishing",
    interior: "Surface wear",
    comesWith: "Museum Grades Certificate of Authenticity, strap, clochette",
    size: { base: '13"', height: '10"', depth: '6.5"', drop: '4"' },
  },
  {
    id: "1912987",
    slug: "saint-laurent-grain-de-poudre-medium-kate-black-1912987",
    brand: "Saint Laurent",
    name: "Grain De Poudre Medium Kate Black",
    price: 1395,
    estRetail: 2650,
    savingsPercent: 47,
    condition: "Excellent",
    color: "Black",
    material: "Leather",
    bagType: "Crossbody Bags",
    images: ["/images/products/ysl-kate-1.jpg"],
    description:
      "This is an authentic SAINT LAURENT Grain De Poudre Medium Kate in Black. This elegant clutch on chain is crafted of textured grained leather in black.",
    itemNumber: "1912987",
    exterior: "Minor surface wear",
    hardware: "Light scratch(es)",
    interior: "Clean",
    comesWith: "Museum Grades Certificate of Authenticity, chain strap",
    size: { base: '10"', height: '6"', depth: '2"', drop: '22"' },
  },
  {
    id: "1924098",
    slug: "christian-dior-oblique-saddle-bag-blue-1924098",
    brand: "Christian Dior",
    name: "Oblique Saddle Bag Blue",
    price: 2850,
    estRetail: 3800,
    savingsPercent: 25,
    condition: "Excellent",
    color: "Blue",
    material: "Canvas",
    bagType: "Crossbody Bags",
    images: ["/images/products/dior-saddle-1.jpg"],
    description:
      "This is an authentic CHRISTIAN DIOR Oblique Saddle Bag in Blue. This iconic saddle bag is crafted of Dior Oblique jacquard canvas in blue.",
    itemNumber: "1924098",
    exterior: "Minor surface wear",
    hardware: "Light scratch(es)",
    interior: "Clean",
    comesWith: "Museum Grades Certificate of Authenticity, strap",
    size: { base: '10"', height: '8"', depth: '3"', drop: '7"' },
  },
];

export const seedCategories = [
  { name: "Crossbody", image: "/images/cat-crossbody.jpg", href: "/collections/all-bags?bagType=Crossbody+Bags" },
  { name: "Totes", image: "/images/cat-totes.jpg", href: "/collections/all-bags?bagType=Totes" },
  { name: "Shoulder Bags", image: "/images/cat-shoulder.jpg", href: "/collections/all-bags?bagType=Shoulder+Bags" },
  { name: "Backpacks", image: "/images/cat-backpacks.jpg", href: "/collections/all-bags?bagType=Backpacks" },
  { name: "Belt Bags", image: "/images/cat-belt.jpg", href: "/collections/all-bags?bagType=Belt+Bags" },
  { name: "Hobo Bags", image: "/images/cat-hobo.jpg", href: "/collections/all-bags?bagType=Hobo+Bags" },
  { name: "Bucket Bags", image: "/images/cat-bucket.jpg", href: "/collections/all-bags?bagType=Bucket+Bags" },
  { name: "Clutches", image: "/images/cat-clutches.jpg", href: "/collections/all-bags?bagType=Clutches" },
  { name: "Satchels", image: "/images/cat-satchels.jpg", href: "/collections/all-bags?bagType=Satchels" },
];
